version: '3'
services:
  web:
    image: nginx:alpine
    volumes:
      - './etc/default.conf:/etc/nginx/conf.d/default.conf'
      - './app:/var/www/html'
    ports:
      - '80:80'
      - '3000:443'
    command: /bin/sh -c "nginx -g 'daemon off;'"
    restart: always
    depends_on:
      - php
      - mysqldb
  php:
    image: nanoninja/php-fpm:latest
    restart: always
    volumes:
      - './app:/var/www/html'
  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - '8000:80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    restart: always
    depends_on:
      - mysqldb
  mysqldb:
    image: mariadb:latest
    container_name: mysql
    restart: always
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=game
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_USER=root
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
    ports:
      - '8989:3306'
    volumes:
      - './data/db/mysql:/var/lib/mysql'
